Repository toss/es-toolkit, pull requests merged in 2025-08, with the labels that each got.

#1332 fix: Add missing parameter and return descriptions to isNil docs
  docs/ja/reference/predicate/isNil.md
  docs/ko/reference/predicate/isNil.md
  docs/reference/predicate/isNil.md
  docs/zh_hans/reference/predicate/isNil.md
Labels: documentation

#1331 fix: Fix incorrect return type of isInteger docs
  docs/ja/reference/compat/predicate/isInteger.md
  docs/ko/reference/compat/predicate/isInteger.md
  docs/reference/compat/predicate/isInteger.md
  docs/zh_hans/reference/compat/predicate/isInteger.md
Labels: documentation

#1330 fix: Fix incorrect return type description for isFunction docs
  docs/ja/reference/predicate/isFunction.md
  docs/ko/reference/predicate/isFunction.md
Labels: documentation

#1329 fix: Fix incorrect callback key parameter type in each docs
  docs/ja/reference/compat/array/each.md
  docs/ko/reference/compat/array/each.md
  docs/reference/compat/array/each.md
Labels: documentation

#1328 fix: Align fill docs interface with implementation JSDoc across
  docs/ja/reference/array/fill.md
  docs/ko/reference/array/fill.md
  docs/reference/array/fill.md
  docs/zh_hans/reference/array/fill.md
Labels: documentation

#1314 Fix: correct method name from toNumber to toFinite in JSDoc and official documentation
  docs/ja/reference/compat/util/toFinite.md
  docs/ko/reference/compat/util/toFinite.md
  docs/reference/compat/util/toFinite.md
  docs/zh_hans/reference/compat/util/toFinite.md
  src/compat/util/toFinite.ts
Labels: documentation

#1313 fix: update lastIndexOf example with Korean text
  docs/ko/reference/compat/array/lastIndexOf.md
Labels: documentation

#1308 fix(tests): Fix test in US time zones
  src/predicate/isEqualWith.spec.ts
Labels: test

#1309 fix(omit): Avoid unnecessary deep cloning in `omit`
  src/compat/object/omit.spec.ts
  src/compat/object/omit.ts
Labels: bug, compat
